/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import brushTestPart2 from './brushPart2.test'
import drawingTsMatrixTest from './matrix.test'
import penPart3Test from './penPart3.test'
import drawingTsRegionTestPart2 from './region.test'
import rectUtilsTestPart2 from './rectUtilsPart2.test'

import brushTest from './color4f/brush.test'
import drawingTsPath3Test from './path/path3.test'
import drawingTsPath4Test from './path/path4.test'
import drawingTsPath2Test from './path/path2.test'
import drawingTsPath5Test from './path/path5.test'
import drawingTsPathTest from './path/path.test'
import drawingCodeTest from './path/drawingCodeTest.test'
import drawingTsCanvasTest from './path/canvas.test'
import drawingTsCanvasPart2Test from './path/canvasPart2.test'
import drawingTsCanvasPart7Test from './path/canvasPart7.test'
import drawingTsRegionTest from './path/region.test'
import graphicDrawingPathTest from './path/graphicDrawingPathTest.test'
import penPart2Test from './color4f/penPart2.test'
import drawingTsCanvasPart5Test from './rect/canvasPart5.test'
import rectUtilsTest from './rect/rectUtils.test'
import graphicsDrawingTest from './graphicsDrawing.test'
import graphicsDrawingTest1 from './graphicDrawing_1.test'
import graphicsDrawingTest2 from './graphicDrawing_2.test'
import fontPart2Test from './fontPart2.test'
import fontPart3Test from './fontPart3.test'
import fontTest from './font.test'
import graphicDrawingFontInterfaceTest from './graphicDrawingFontInterface.test'
import graphicDrawingPathTestPart2 from './graphicDrawingPathTestPart2.test'
import pathEffectTest from './pathEffect.test'
import penTest from './pen.test'
import imageFilterTest from './imageFilter.test'
import shadowEffectTest from './shaderEffect.test'
import shadowLayerTest from './shadowLayer.test'
import colorFilterTest from './colorFilter.test'
import colorFilterTest_ from './static/colorFilter_.test'
import drawingCodeTestPart2 from './drawingCodeTestPart2.test'
import penPart4Test from './penPart4.test'
import maskFilterTest from './maskFilter.test'
import drawingTsCanvasPart3Test from './canvasPart3.test'
import drawingTsCanvasPart4Test from './canvasPart4.test'
import drawingTsCanvasTest_ from './static/canvas_.test'
import drawingTsCanvasPart2Test_ from './static/canvasPart2_.test'
import penPart2Test_ from './static/penPart2_.test'

export default function testsuite() {
  brushTestPart2()
  drawingTsMatrixTest()
  penPart3Test()
  drawingTsRegionTestPart2()
  rectUtilsTestPart2()
  brushTest()
  penPart2Test()
  drawingTsCanvasTest()
  drawingTsCanvasPart2Test()
  drawingTsCanvasPart7Test()
  drawingCodeTest()
  graphicDrawingPathTest()
  drawingTsPathTest()
  drawingTsPath2Test()
  drawingTsPath3Test()
  drawingTsPath4Test()
  drawingTsPath5Test()
  drawingTsRegionTest()
  drawingTsCanvasPart5Test()
  rectUtilsTest()
  graphicsDrawingTest()
  graphicsDrawingTest1()
  graphicsDrawingTest2()
  fontPart2Test()
  fontPart3Test()
  fontTest()
  graphicDrawingFontInterfaceTest()
  graphicDrawingPathTestPart2()
  pathEffectTest()
  penTest()
  imageFilterTest()
  shadowEffectTest()
  shadowLayerTest()
  colorFilterTest()
  colorFilterTest_()
  drawingCodeTestPart2()
  penPart4Test()
  maskFilterTest()
  drawingTsCanvasPart3Test()
  drawingTsCanvasPart4Test()
  drawingTsCanvasTest_()
  drawingTsCanvasPart2Test_()
  penPart2Test_()
}